experiment:
  title: Single-Layer MLP for MNIST classification
  mode: classification

  model:
    network_name: mlp
    in_dim: 784
    hidden_dims: [300]
    out_dim: 10
  
  training:
    dataset_name: mnist
    n_epochs: 100
    batch_size: 128
    output_path: ./io/output/mlp

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42