experiment:
  mode: vae
  
  model:
    network_name: nvae
    latent_dim: 10
    adjoint: False
    rtol: 1.e-7
    atol: 1.e-9 
    method: dopri5
  
  training:
    dataset_name: mnist
    n_epochs: 50
    batch_size: 128
    kl_weight: 1.e-3
    output_path: ./io/output/nvae

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42