experiment:
  model:
    network_name: odenet
    out_dim: 10
  
  training:
    n_epochs: 10
    batch_size: 128
    output_path: ./output/odenet

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42