experiment:
  title: ResNet for MNIST classification
  mode: classification

  model:
    network_name: resnet
    num_res_blocks: 6
    kernel_size: 3
    num_filters: [64, 64]
    num_channels: 1
    out_dim: 10
  
  training:
    dataset_name: mnist
    n_epochs: 100
    batch_size: 128
    output_path: ./io/output/resnet

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42