experiment:
  title: ResNet for VOC segmentation
  mode: segmentation

  model:
    network_name: resnet
    num_res_blocks: 6
    out_dim: 21
  
  training:
    dataset_name: voc_segmentation
    n_epochs: 30
    batch_size: 128
    output_path: ./io/output/resnet_segmentation

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42