experiment:
  title: ODENet without adjoint method and rk4 solver for MNIST classification
  mode: classification

  model:
    network_name: odenet
    out_dim: 10
    adjoint: False
    rtol: 1.e-7
    atol: 1.e-9 
    method: rk4
  
  training:
    dataset_name: mnist
    n_epochs: 10
    batch_size: 128
    output_path: ./io/output/rknet

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42