experiment:
  model:
    network_name: slmlp
    in_dim: 784
    out_dim: 10
    hidden_dim: 300
  
  training:
    n_epochs: 30
    batch_size: 128
    output_path: ./output/slmlp

  optimizer:
    optimizer_name: adam
    lr: 0.0001
    betas: [0.9, 0.999]
    eps: 1.e-7
    weight_decay: 1.e-4
    amsgrad: false

  seed: 42